### ISSUE TITLE
Methods may end with ?

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/vs.language.ooc#36]
Although they shouldn't, we cannot avoid it.

**Comment by thomasfanell** [comment]
Yeah since rock allows it.

**Comment by thomasfanell** [comment]
I could make it so that the highlighter marks any function that ends with `?` invalid.

**Comment by marcusnaslund** [comment]
Ohhh, nevermind, I was using `atom` for its global search-replace and there methods couldn't end with `?` without being highlighted wrongly.
I don't think we should mark them as invalid since there is no other valid way of doing it.
