### ISSUE TITLE
Color TODO and FIXME as was the case in Atom

### ISSUE THREAD

**Issue by marcusnaslund** [cogneco/vs.language.ooc#5]
Since we use these words a lot in kean, it would be nice to have them coloured so that they stand out.

**Comment by thomasfanell** [comment]
If i'm not mistaken, Atom use a special plugin to do that. I tried to make it so Code scans the comments for those two tokens a few weeks ago, but I could not come up with a good way. I can look into it again soon.

**Comment by davidhesselbom** [comment]
I don't mean to imply it's an easy fix or anything, but, it also works in gedit, just fyi.

**Comment by thomasfanell** [comment]
I am aware of that. :)
